### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by daniel-sousa-me** [etherdelta/etherdelta.github.io#162]
I am trying to use Etherdelta's API, but it is very hard to understand the documentation

> sha256(contractAddr, tokenGet, amountGet, tokenGive, amountGive, expires, nonce)

What do you mean by this line? How are the different parts joined for the hashing function?

**Comment by zackcoburn** [comment]
Here's a gist to help you:
https://gist.github.com/zackcoburn/4e73cfbf28e25d12041b4c19627ea60a

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by daniel-sousa-me** [comment]
I don't know how to run that code, but I have tried following it.
Is this the right string to pass onto sha256?

>8d12a197cb00d4747a1fe03395095ce2a5cc68198f3470a7388c05ee4e7af3d01d8c722b0ff523740000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000429d069189e000000000000000000000000000000000000000000000000000000000000004c4b40000000000000000000000000000000000000000000000000000000000001e240

**Comment by zackcoburn** [comment]
Yep, that looks correct (I haven't counted zeros or anything, but it would
look something like that). sha256 in a smart contract will just tightly
pack the arguments. (
https://ethereum.stackexchange.com/questions/3715/arguments-of-the-sha256-function-in-solidity
describes it a bit more, but the example code does it for you.)

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by daniel-sousa-me** [comment]
If you could post the output of 

>console.log(condensed);
console.log(hash);
console.log(sig);
console.log(testSig(sig.msg, sig, user));

I think I can figure it out and stop bugging you x)

**Comment by daniel-sousa-me** [comment]
I did an order in etherdelta.com then intercepted the call to the api and I am trying to reproduce it in python without any luck.

Can you run the code in that gist and tell me the outputs of the `console.log`s? I should be able to figure out what's wrong from there

**Comment by zackcoburn** [comment]
Sure, here's the full output:

[ '0x8d12a197cb00d4747a1fe03395095ce2a5cc6819',
  '0x8f3470a7388c05ee4e7af3d01d8c722b0ff52374',
  { [String: '1000000000000000000'] s: 1, e: 18, c: [ 10000 ] },
  '0x0000000000000000000000000000000000000000',
  { [String: '300000000000000000'] s: 1, e: 17, c: [ 3000 ] },
  5000000,
  123456 ]
8d12a197cb00d4747a1fe03395095ce2a5cc68198f3470a7388c05ee4e7af3d01d8c722b0ff523740000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000429d069189e000000000000000000000000000000000000000000000000000000000000004c4b40000000000000000000000000000000000000000000000000000000000001e240
0xb60215f455a8b0e90a79df0f28933397059e070b23029820526165f817af6759
{ r: '0x1f4ab7e26711f235331edc67bd697fd0c7628dd5ffcab333870640dee329914b',
  s: '0x2bce958fb3ee54817b1d5102e364a9164f46f732f4a02a9d5cd9569b085f2112',
  v: 27,
  msg: '0x757a9498e7b511f9c74a414de4207ee392642d4ef53510aba55e66330f85d3e8'
}
true

  contract Test {
    function test1() constant returns (bool) {
      address user = 0x88ebA77DC1b9E627e963020cE1f8dE9Fcf25edbD;
      uint8 v = 27;
      bytes32 r =
0x1f4ab7e26711f235331edc67bd697fd0c7628dd5ffcab333870640dee329914b;
      bytes32 s =
0x2bce958fb3ee54817b1d5102e364a9164f46f732f4a02a9d5cd9569b085f2112;
      address tokenGive = 0x0000000000000000000000000000000000000000;
      address tokenGet = 0x8f3470a7388c05ee4e7af3d01d8c722b0ff52374;
      uint amountGive = 300000000000000000;
      uint amountGet = 1000000000000000000;
      uint expires = 5000000;
      uint nonce = 123456;
      bytes32 hash = sha256(0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,
tokenGet, amountGet, tokenGive, amountGive, expires, nonce);
      bytes32 msg = sha3("\x19Ethereum Signed Message:\n32", hash);
      return ecrecover(msg, v, r, s) == user;
    }
    function test2() constant returns (bool) {
      address user = 0x88ebA77DC1b9E627e963020cE1f8dE9Fcf25edbD;
      uint8 v = 27;
      bytes32 r =
0x1f4ab7e26711f235331edc67bd697fd0c7628dd5ffcab333870640dee329914b;
      bytes32 s =
0x2bce958fb3ee54817b1d5102e364a9164f46f732f4a02a9d5cd9569b085f2112;
      bytes32 msg =
0x757a9498e7b511f9c74a414de4207ee392642d4ef53510aba55e66330f85d3e8;
      return ecrecover(msg, v, r, s) == user;
    }
  }

Deleted order because available volume too low.



Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by daniel-sousa-me** [comment]
Thank you very much!

After a lot of tinkering with data types and finding out I can't copy-paste strings, I was able to reproduce this in python 😃

**Comment by niranjanshr13** [comment]
@daniel-sousa-me can i get the copy of the python version of it.

**Comment by HarrySonghurst** [comment]
@daniel-sousa-me can I get a copy too ;)
