### ISSUE TITLE
Unable to deposit CNX

### ISSUE THREAD

**Issue by adamsmd** [etherdelta/etherdelta.github.io#201]
When I attempt to deposit CNX, the transaction always fails.

For example, EtherScan reports that this transaction
https://etherscan.io/tx/0xb2bf05320ae379a21e841e31c1f5f698f8520d654c0bfbaae913bb08aba250f5
failed with "Warning! Error encountered during contract execution [Bad instruction]" (which if I understand correctly means solidity did a `throw`).  I don't know enough to debug this, so any help in determining the cause would be appreciated.

**Comment by zackcoburn** [comment]
It looks like you only accepted the deposit() transaction, but you should
also have an approve() transaction right before. Did you see two
transactions popup in your MetaMask?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

On Mon, Oct 23, 2017 at 12:57 PM, Michael D. Adams <notifications@github.com

**Comment by adamsmd** [comment]
I see only one transaction popup in MetaMask.  Is there any data I can collect or tests I can run to determine why?

**Comment by zackcoburn** [comment]
It's actually impossible to say because CNX hasn't verified their token
code on Etherscan:
https://etherscan.io/address/0x94d6b4fb35fb08cb34aa716ab40049ec88002079#code
.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by Bill-Niz** [comment]
hi,
Did you fixed this? @adamsmd

**Comment by adamsmd** [comment]
It is not fixed, I think this is an upstream issue with the CNX token.
