### ISSUE TITLE
API Documentation: Deleted Order Example

### ISSUE THREAD

**Issue by adamsmd** [etherdelta/etherdelta.github.io#214]
Could you add to the API documentation an example of a message containing a deleted order?

**Comment by zackcoburn** [comment]
I don't have an example readily available, but it would look similar to
this:
https://github.com/etherdelta/etherdelta.github.io/blob/master/bots/service.js#L299

Except instead of the trade function, it's the cancel function.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

On Fri, Oct 27, 2017 at 10:51 AM, Michael D. Adams <notifications@github.com

**Comment by dj2ball** [comment]
When the order is emitted to your socket client, if it is deleted it will contain a 'deleted' key with a value of TRUE - so you just need to write a filter to check for that key and then do whatever you want with deleted orders. It's working pretty well in my client.

**Comment by adamsmd** [comment]
Thank you @dj2ball, that clarifies things.
