### ISSUE TITLE
R/S/V signature security when taking orders

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#251]
Hey there,

As part of my refactoring work I am trying to establish a delineation between DTOs and Domain entities. In my ideal world, I would have, for instance, an Order class which encapsulates generic Order information across multiple exchanges. I would map an EtherDelta Order DTO into a generic order and vice-versa.

When interacting with exchanges that use an order matchmaking system there is no need to take a specific order. One indicates how much they want to market buy and receive it. Here, things are a bit different, and I am struggling with understanding if this means I need a completely separate Domain entity.

So, my first question is:

- Am I required to preserve the original r/s/v values for an order when attempting to take it? Am I able to sign my own?

In your bots example for taking an order I see these actions being taken:

- Receive orders from server, store in order book.
- Determine order to take by analyzing order book.
- Pass r/s/v from the order into the contract's `trade` method.

This effectively reuses the signature of the person who put the trade into the system.

Then, that data is hashed, and I sign my own signature ontop of it to verify that I am cool with it.

What I'm struggling with is... why do I, as a consumer of the service, care about confirming the validity of the order to the ED smart contract?

I suppose this gets somewhat close to match making. I feel like I should be able to say "Take [an order which has this traits] and trade it with me. Here is my signature to say I want to do this." At that point, if an order exists, the trade occurs. Otherwise, it does not. All of this logic seems the same as what you currently have... just.. no need to match on r/s/v of the originating signature.

Is there anything possibly malicious about this sort of change? What are your thoughts on it? It would greatly simplify what is necessary to unify logic across multiple exchanges.

I suppose I have similar concerns with `expires`, `nonce`, and `user`. These all seem like kinda irrelevant fields for me to communicate to ED given that this information came *from* ED.

**Comment by zackcoburn** [comment]
You do need to pass all the original order information to the trade()
function (and then sign the whole transaction with your private key). The
reason is that the smart contract and the order book are separate. The
order book is an off-chain mechanism, so you have to present everything
about the order you want to trade to the smart contract so that the smart
contract can verify that the person who placed the order actually signed
it, and that the order is still valid (funded and unexpired). To do what
you're suggesting would require storing (and sorting) orders on-chain,
which has some heavy gas costs and limitations.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Hummm. I think I see now, but just reiterating to confirm my understanding..

In order to place an order, I provide all the necessary details to create an on-chain transaction to your off-chain orderbook via websocket.

I receive orders, including r/s/v, from your server via websocket.

I believe you are keeping an in-memory representation of the order book on your server. When I submit an order your server does *some stuff* and then puts my bid/ask into the blockchain. Is this correct? It would explain why cancelling an order takes gas, and why placing an order on-chain is possible, but would (apparently) not appear in ED's GUI.

Now, if I want to take an order, I am able to do that completely on-chain and certainly would need the original r/s/v values to do so. I would need to get this information from your server if I did not have it. Your server *does seem to have the information*, but offloading this responsibility to clients makes it cheaper for you to run a server. Fair enough.

The thing that gets me though... is... wtf is your server doing? A bit of a rhetorical question, but, IMO, something isn't adding up.

Your GUI is able to update when I take an order, but this is strictly an on-chain interaction with the smart contract. So, it's clear that your GUI has the ability to detect changes (via EtherScan's API) and refresh the UI accordingly.

It would seem like this is also possible to do with placing orders on-chain, but you noted elsewhere that the UI wouldn't update for that. Why not? Surely it's the same process here? Also, if it is true that I am able to place orders on-chain myself then that would seem like proof that your server is not maintaining any relevant information, no? It would be more challenging to detect all the orders on EtherScan, but they must be there if cancelling an order takes gas.

**Comment by zackcoburn** [comment]
When you submit an order to the off-chain order book, all it does is check
to make sure the order is valid (signature is valid, there are enough funds
deposited backing up the order), and then adds the order to its list. It
does not send anything to the blockchain. There is a "vestigial" function
in the smart contract for "placing an order on-chain -- in the event log,"
but it's not currently in use. The order book server never writes to the
blockchain, it only reads from the blockchain (processing the event log so
the browser doesn't have to do this), and processes incoming off-chain
orders. This whole magic works because of signatures. The off-chain orders
don't have to be stored on-chain, because all it takes is a signature to
prove that someone, wanting to do a trade, placed a resting order in the
off-chain order book.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Hummm, okay. Let me see if I understand this fully, then.

- The EtherDelta smart contract has no knowledge of whether an order is in the orderbook. All it cares about is receiving a trade notification which has a valid signature from both parties.

- Cancelling an order is an on-chain action, even though the order itself is stored off-chain, so that the EtherDelta smart contract knows that the order is OFF the orderbook, but it never knew about it being on prior. Essentially, a cancel order marks a signature as invalid.

- Taking an order is an on-chain action which involves describing to the contract two users signatures for two orders. After an order is taken, the signatures are invalidated (similar to cancel) to prevent duplicate trades re-using the same signature (presumably) otherwise I could force someone to repeatedly bid on my order, if they did once, by repeating their transaction.

Using your server's socket API is necessary for knowing when an order is created, and what orders are already exist, but it is not necessary for knowing when an order was cancelled, taken, or expired. We have all that information on-chain, but you simply repeat it off-chain as a convenience.

**Comment by zackcoburn** [comment]
Exactly. The final interesting tidbit is that the smart contract does allow
for partial fills, so when an order trades, it doesn't get marked as
"traded," but rather the volume that traded is added to the volume that
traded for that order so far.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Hummm. Does that open a security concern?

If I am selling 1000 1ST and someone purchases 100 1ST from the 1000... can't I capture the signature of that order and repeat it assuming everyone's balances are still OK?

I guess that's prevented by the nonce? Since the same nonce multiple times wouldn't be OK, but the nonce is encoded into the hash, so if I wanted to increase it then I would need to have them re-sign?

**Comment by zackcoburn** [comment]
In particular, it's the Ethereum transaction nonce (as opposed to the order
nonce) that prevents that. If someone wanted to repeat the transaction,
they'd need you to sign the same transaction again, but with the next nonce.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
What's the order nonce for, then? Sorry for all the questions! This is all really quite cleverly put together. Now you've got me wanting to try and find security holes in it rather than actually working on my bot, ugh. :)

**Comment by zackcoburn** [comment]
The order nonce is so if you submit the same order (in terms of price,
volume, token, and expiration block) twice, it won't have the same hash.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Ah, yup. Duh. Okay! Got it! Thanks!
