### ISSUE TITLE
who pay the Ethereum fees ?

### ISSUE THREAD

**Issue by happmaoo** [etherdelta/etherdelta.github.io#303]
I just wonder when I buy a coin, who pay the Ethereum fees ? buyer or seller?
what happened when the seller's account doesn't have enough etherum pay the fee?

**Comment by zackcoburn** [comment]
The person who places the order in the order book never pays any fee. The
person who trades against the order pays the gas fee.

On Dec 3, 2017 10:03 PM, "happmaoo" <notifications@github.com> wrote:

I just wonder when I buy a coin, who pay the Ethereum fees ? buyer or
seller?
what happened when the seller's account doesn't have enough etherum pay the
fee?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/etherdelta/etherdelta.github.io/issues/303>, or mute
the thread
