### ISSUE TITLE
Listing request of Adelphoi (ADL)

### ISSUE THREAD

**Issue by R0bini0** [etherdelta/etherdelta.github.io#516]
Hello Team!

We would love to list our Adelphoi Coin "ADL" to your Exchange.

Adelphoi coin (ADL)
ERC 20
Wallet : MEW or other ERC20 Wallets
Symbol: ADL
Max Supply: 100m
Decimals: 18

Website: www.adel.io

TWITTER: https://twitter.com/adelphoi_io

BitcoinTalk: https://bitcointalk.org/index.php?topic=2135312.0

Telegram: https://t.me/Adelphoi

Slack Public: https://adel-signup.herokuapp.com/

https://etherscan.io/address/0x660e71483785f66133548B10f6926dC332b06e61

Adel is a technology incubator for blockchain innovation. Our community collaborates on ideas, and uses the AdelWiki™ to collectively create business plans. Members vote on projects and can become profit participates when they are launched. Expertise within the community brings mentoring, learning, and employment opportunities. Successful projects are re-invested for further growth, or issued as rewards to members. Adel is blockchain agnostic...

Thanks in advance for your help!

**Comment by Winances** [comment]
Dear Sir or Madam,

You are launching your ICO or maybe this one is already done ?

What if your ICO will be already be checked for an exchange listing?

What if your ICO could be granted with a brand new Certified Listing Label ?

It could be a great news for your investors, for your team and for your project also.

That is what is providing AWS Token - All Winances Services Token.

——-
Buying at least 10 000 Aws during our current ICO will allow you to fill the Listing form for a 48 hours Exchange listing on Winances.com.

——-
More than 10 000 ICOs are in progress - More of 10 000 ICOs are already done.

Are they all listed? When will they be listed? For most of them, nobody knows, not even the team.

——
That is why you are welcome to fill our form. An answer will be given within 48hours in a full transparency for everyone.

Our Due Diligence will be performed on very basic files.

Fill our form and display our special AWS Certified Label on your ICO and all your communication supports.

——
Help your investors to be insured you will be listed very soon.

Help your investors to invest much more....

It is a win/win solution.

——-
And once you are done with AWS, hold or resell on exchanges.

More and more ICO will need AWS. AWS price will only increase because of bid on this very particular New Token.

AWS needs you all...

Join now on Winances.com

Thank you
